### ISSUE TITLE
要使用dev分支，master分支有问题，清再readme中声明

### ISSUE THREAD

**Issue by jinghunao** [galaxy-future/bridgx#168]
使用mster分支，造成创建vpc阿里云能看到创建成功，但是dashboard选不了vpc，切换dev分支即可解决，最好再readme中声明哪个分支是最新代码

**Comment by liqunn** [comment]
已经同步最新代码到master，感谢反馈~

**Comment by huzhongx** [comment]
> 使用mster分支，造成创建vpc阿里云能看到创建成功，但是dashboard选不了vpc，切换dev分支即可解决，最好再readme中声明哪个分支是最新代码

感谢建议，我们后续只保留一个分支。
