### ISSUE TITLE
[Task][HuaweiCloud] Support EIP Operation

### ISSUE THREAD

**Issue by lbsu** [galaxy-future/bridgx#194]
### **背景**
为 BridgX 增加支持华为云 EIP 所需的底层 openapi 对接。

### **任务**
-  完成 华为云 的接口对接；
    AllocateEip
    GetEips
    ReleaseEip
    AssociateEip
    DisassociateEip
    DescribeEip
    ConvertPublicIpToEip
(代码入口：internal/providers/huawei/eip.go)
- 完成相应的单元测试；
(代码入口：internal/providers/huawei/eip_test.go)

### **技能要求和编程语言**
- 熟悉华为云 openapi 对接；
- Golang；

### **预期完成结果**
- 完成接口对接；
- 有相对完整的单元测试用例；

### **关于 PR**
从 feat-task-20221017 分支开新分支，完成后向 feat-task-20221017 分支提 PR

### **参考**
[bridgx-20221017 任务对接指南](https://galaxy-future.feishu.cn/docx/XurBd35uCoGbF6xZdricc6mrnAg)

------
开发者可扫码添加官方助手，入群沟通 :)

![](https://www.galaxy-future.com/image/qr_cs_362e7.jpg)

**Comment by baiyutang** [comment]
I will do this task. please assign to me.

**Comment by baiyutang** [comment]
this issue can be closed
