### ISSUE TITLE
[Task][TencentCloud] Support TCR Operation

### ISSUE THREAD

**Issue by lbsu** [galaxy-future/bridgx#197]
### **背景**
为 BridgX 增加支持腾讯云容器镜像服务所需的底层 openapi 对接。

### **任务**
-  完成腾讯云的接口对接；
	ContainerInstanceList
	EnterpriseNamespaceList
	PersonalNamespaceList
	EnterpriseRepositoryList
	PersonalRepositoryList
	EnterpriseImageList
	PersonalImageList
(代码入口：internal/providers/tencent/cr.go)
- 完成相应的单元测试；
(代码入口：internal/providers/tencent/cr_test.go)

### **技能要求和编程语言**
- 熟悉腾讯云 openapi 对接；
- Golang；

### **预期完成结果**
- 完成接口对接；
- 有相对完整的单元测试用例；

### **关于 PR**
从 feat-task-20221017 分支开新分支，完成后向 feat-task-20221017 分支提 PR

### **参考**
[bridgx-20221017 任务对接指南](https://galaxy-future.feishu.cn/docx/XurBd35uCoGbF6xZdricc6mrnAg)

------
开发者可扫码添加官方助手，入群沟通 :)

![](https://www.galaxy-future.com/image/qr_cs_362e7.jpg)

**Comment by zhuyaguang** [comment]
I will do this task. please assign to me.
